---
apiVersion: v1
kind: Service
metadata:
  name: couchdb
  labels:
    app: couchdb
spec:
  ports:
    - port: 5984
      protocol: TCP
      targetPort: 5984
  type: LoadBalancer
  selector:
    app: couchdb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: couchdb-deployment
  labels:
    app: couchdb
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
        - image: couchdb:latest
          name: couchdb
          env:
            - name: COUCHDB_USER
              value: 'admin'
            - name: COUCHDB_PASSWORD
              value: 'password'
          ports:
            - containerPort: 5984
          volumeMounts:
            - name: couchdb-storage
              mountPath: /opt/couchdb/data
      volumes:
        - name: couchdb-storage
          persistentVolumeClaim:
            claimName: couchdb-claim