---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-volume
  labels:
    type: local
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/data/couchdb # This would only persist in a single-node. Use dynamic provisioning for multi-node clusters (paid). No need to create a Persistent Volume if you will use dynamic provisioning.
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: "" # Comment this line to use dynamic provisioning (paid)
  name: couchdb-claim
  labels:
    app: watson-reviews
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi